version: '3'

services:
  eva:
    build: .
    container_name: eva-sinvello
    restart: always
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_PROMPT_ID=${OPENAI_PROMPT_ID}
    labels:
      - "traefik.enable=true"
      - "traefik.backend=eva"
      - "traefik.frontend.rule=Host:eva.sinvelloporlaser.es"
      - "traefik.port=8501"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=eva.sinvelloporlaser.es"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"
    networks:
      - web
    volumes:
      - ./:/app

networks:
  web:
    external: true
